import type { ChecklistTemplateItem, recurrenceEnum } from "@/db/schema/catalog";

type Recurrence = (typeof recurrenceEnum.enumValues)[number];

export type CatalogSeedService = {
  name: string;
  slug: string;
  description?: string;
  basePricePaise: number;
  govtFeePaise?: number;
  estimatedDays: number;
  isRecurring: boolean;
  recurrence?: Recurrence;
  checklistTemplate: ChecklistTemplateItem[];
  requiredDocuments: string[];
};

export type CatalogSeedCategory = {
  name: string;
  sort: number;
  services: CatalogSeedService[];
};

export type CatalogSeedVertical = {
  name: string;
  sort: number;
  categories: CatalogSeedCategory[];
};

export const CATALOG_SEED: CatalogSeedVertical[] = [
  {
    name: "Company Registration Services",
    sort: 1,
    categories: [
      {
        name: "Company Registration",
        sort: 1,
        services: [
          {
            name: "Sole Proprietorship",
            slug: "proprietorship-registration",
            description: "Sole proprietorship setup with basic registrations.",
            basePricePaise: 99900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Apply for Udyam registration", dayOffset: 2 },
              { title: "Apply for GST registration (if applicable)", dayOffset: 5 },
              { title: "Open current bank account", dayOffset: 5 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
          {
            name: "Partnership Firm",
            slug: "partnership-registration",
            description: "Drafting and registration of a Partnership Deed.",
            basePricePaise: 899900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Draft Partnership Deed", dayOffset: 3 },
              { title: "Notarize deed", dayOffset: 5 },
              { title: "Apply for PAN in firm name", dayOffset: 7 },
              { title: "Register with Registrar of Firms (optional)", dayOffset: 10 },
            ],
            requiredDocuments: [
              "PAN Card of all partners",
              "Aadhaar Card of all partners",
              "Address proof of firm's place of business",
            ],
          },
          {
            name: "One Person Company - OPC",
            slug: "opc-registration",
            description: "Incorporation of a One Person Company.",
            basePricePaise: 599900,
            estimatedDays: 7,
            isRecurring: false,
            checklistTemplate: [
              { title: "Name approval (RUN)", dayOffset: 2 },
              { title: "Obtain Digital Signature Certificate", dayOffset: 3 },
              { title: "Draft MOA & AOA with nominee consent", dayOffset: 5 },
              { title: "File SPICe+ with ROC", dayOffset: 7 },
              { title: "Receive Certificate of Incorporation", dayOffset: 7 },
            ],
            requiredDocuments: [
              "PAN Card of all directors/partners",
              "Aadhaar Card of all directors/partners",
              "Passport-size photograph",
              "Address proof of registered office",
              "NOC from property owner",
            ],
          },
          {
            name: "Limited Liability Partnership - LLP",
            slug: "llp-registration",
            description: "Incorporation of a Limited Liability Partnership.",
            basePricePaise: 699900,
            estimatedDays: 7,
            isRecurring: false,
            checklistTemplate: [
              { title: "Name approval (RUN-LLP)", dayOffset: 2 },
              { title: "Obtain Digital Signature Certificates", dayOffset: 3 },
              { title: "Draft LLP Agreement", dayOffset: 6 },
              { title: "File FiLLiP with ROC", dayOffset: 7 },
              { title: "Receive Certificate of Incorporation", dayOffset: 7 },
            ],
            requiredDocuments: [
              "PAN Card of all directors/partners",
              "Aadhaar Card of all directors/partners",
              "Passport-size photograph",
              "Address proof of registered office",
              "NOC from property owner",
            ],
          },
          {
            name: "Private Limited Company",
            slug: "pvt-ltd-registration",
            description: "End-to-end incorporation of a Private Limited Company via SPICe+.",
            basePricePaise: 1099900,
            estimatedDays: 7,
            isRecurring: false,
            checklistTemplate: [
              { title: "Name approval (RUN)", dayOffset: 2 },
              { title: "Obtain Digital Signature Certificates", dayOffset: 3 },
              { title: "Draft MOA & AOA", dayOffset: 5 },
              { title: "File SPICe+ with ROC", dayOffset: 7 },
              { title: "Receive Certificate of Incorporation", dayOffset: 7 },
            ],
            requiredDocuments: [
              "PAN Card of all directors/partners",
              "Aadhaar Card of all directors/partners",
              "Passport-size photograph",
              "Address proof of registered office",
              "NOC from property owner",
            ],
          },
          {
            name: "Public Limited Company",
            slug: "public-limited-company",
            basePricePaise: 1299900,
            estimatedDays: 10,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify promoter/partner KYC documents", dayOffset: 2 },
              { title: "Prepare & file application", dayOffset: 6 },
              { title: "Respond to department queries (if any)", dayOffset: 8 },
              { title: "Receive registration/certificate", dayOffset: 10 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
          {
            name: "Section 8 Company",
            slug: "section-8-company",
            basePricePaise: 1899900,
            estimatedDays: 10,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify promoter/partner KYC documents", dayOffset: 2 },
              { title: "Prepare & file application", dayOffset: 6 },
              { title: "Respond to department queries (if any)", dayOffset: 8 },
              { title: "Receive registration/certificate", dayOffset: 10 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
          {
            name: "Partnership Deed",
            slug: "partnership-deed",
            basePricePaise: 199900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify promoter/partner KYC documents", dayOffset: 1 },
              { title: "Prepare & file application", dayOffset: 3 },
              { title: "Respond to department queries (if any)", dayOffset: 4 },
              { title: "Receive registration/certificate", dayOffset: 5 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
          {
            name: "Partnership Deed with Notary",
            slug: "partnership-deed-with-notary",
            basePricePaise: 399900,
            estimatedDays: 10,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify promoter/partner KYC documents", dayOffset: 2 },
              { title: "Prepare & file application", dayOffset: 6 },
              { title: "Respond to department queries (if any)", dayOffset: 8 },
              { title: "Receive registration/certificate", dayOffset: 10 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
          {
            name: "Nidhi Company Registration",
            slug: "nidhi-company-registration",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify promoter/partner KYC documents", dayOffset: 3 },
              { title: "Prepare & file application", dayOffset: 9 },
              { title: "Respond to department queries (if any)", dayOffset: 13 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
          {
            name: "Producer Company Registration",
            slug: "producer-company-registration",
            basePricePaise: 1499900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify promoter/partner KYC documents", dayOffset: 3 },
              { title: "Prepare & file application", dayOffset: 9 },
              { title: "Respond to department queries (if any)", dayOffset: 13 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Address proof",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Registration & Licensing",
    sort: 2,
    categories: [
      {
        name: "Registration Services",
        sort: 1,
        services: [
          {
            name: "UDYAM/MSME",
            slug: "msme-udyam-registration",
            description: "Udyam registration for MSME recognition.",
            basePricePaise: 49900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Verify Aadhaar & PAN details", dayOffset: 1 },
              { title: "Submit Udyam application", dayOffset: 2 },
              { title: "Receive Udyam certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Aadhaar Card", "PAN Card", "Business address proof"],
          },
          {
            name: "GST Registration",
            slug: "gst-registration",
            description: "New GST registration and GSTIN allotment.",
            basePricePaise: 49900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application (REG-01)", dayOffset: 1 },
              { title: "Submit application with documents", dayOffset: 2 },
              { title: "Respond to any department query", dayOffset: 5 },
              { title: "Receive GSTIN", dayOffset: 5 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Address proof of business",
              "Bank account statement/cancelled cheque",
              "Passport-size photograph",
            ],
          },
          {
            name: "Import Export Code - IEC",
            slug: "iec-registration",
            description: "IEC allotment from DGFT for import/export businesses.",
            basePricePaise: 149900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare DGFT application", dayOffset: 1 },
              { title: "Submit application with documents", dayOffset: 2 },
              { title: "Receive IEC certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["PAN Card", "Bank certificate/cancelled cheque", "Address proof"],
          },
          {
            name: "FSSAI Registration",
            slug: "fssai-registration",
            description: "Food business FSSAI basic registration/license.",
            basePricePaise: 99900,
            estimatedDays: 7,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 2 },
              { title: "Submit application on FoSCoS", dayOffset: 3 },
              { title: "Respond to queries", dayOffset: 7 },
              { title: "Receive FSSAI certificate", dayOffset: 7 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Address proof of food business",
              "Passport-size photograph",
            ],
          },
          {
            name: "ESIC Registration",
            slug: "esic-registration",
            basePricePaise: 399900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 1 },
              { title: "Submit application to department", dayOffset: 2 },
              { title: "Respond to department queries", dayOffset: 4 },
              { title: "Receive registration/certificate", dayOffset: 5 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "EPF Registration",
            slug: "epf-registration",
            basePricePaise: 399900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 1 },
              { title: "Submit application to department", dayOffset: 2 },
              { title: "Respond to department queries", dayOffset: 4 },
              { title: "Receive registration/certificate", dayOffset: 5 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Professional Tax Registration",
            slug: "professional-tax-registration",
            basePricePaise: 399900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "PAN Registration",
            slug: "pan-registration",
            basePricePaise: 29900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "TAN Registration",
            slug: "tan-registration",
            basePricePaise: 39900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Trust Registration",
            slug: "trust-registration",
            basePricePaise: 899900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "APEDA Registration",
            slug: "apeda-registration",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Copy Rights Registration",
            slug: "copy-rights-registration",
            basePricePaise: 999900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 1 },
              { title: "Submit application to department", dayOffset: 2 },
              { title: "Respond to department queries", dayOffset: 4 },
              { title: "Receive registration/certificate", dayOffset: 5 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Patent Rights Registration",
            slug: "patent-rights-registration",
            basePricePaise: 3999900,
            estimatedDays: 30,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 6 },
              { title: "Submit application to department", dayOffset: 12 },
              { title: "Respond to department queries", dayOffset: 21 },
              { title: "Receive registration/certificate", dayOffset: 30 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Association",
            slug: "association",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Import Export Code Updation",
            slug: "import-export-code-updation",
            basePricePaise: 99900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 1 },
              { title: "Submit application to department", dayOffset: 1 },
              { title: "Respond to department queries", dayOffset: 2 },
              { title: "Receive registration/certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "GST Cancellation",
            slug: "gst-cancellation",
            basePricePaise: 99900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Trademark Objection",
            slug: "trademark-objection",
            description: "Response to examination report / objection on a filed trademark.",
            basePricePaise: 299900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Review examination report", dayOffset: 2 },
              { title: "Draft reply with evidence of use", dayOffset: 5 },
              { title: "File reply", dayOffset: 5 },
            ],
            requiredDocuments: ["Examination report", "Evidence of use (invoices, ads)"],
          },
          {
            name: "GST Amendment",
            slug: "gst-amendment",
            basePricePaise: 99900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to department", dayOffset: 6 },
              { title: "Respond to department queries", dayOffset: 10 },
              { title: "Receive registration/certificate", dayOffset: 15 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
          {
            name: "Networth Statement",
            slug: "networth-statement",
            basePricePaise: 160000,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 1 },
              { title: "Submit application to department", dayOffset: 1 },
              { title: "Respond to department queries", dayOffset: 2 },
              { title: "Receive registration/certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Business address proof"],
          },
        ],
      },
      {
        name: "Digital Signature Services",
        sort: 2,
        services: [
          {
            name: "DSC Class III - Individual",
            slug: "dsc-class-iii-individual",
            basePricePaise: 99900,
            estimatedDays: 1,
            isRecurring: false,
            checklistTemplate: [
              { title: "Collect applicant documents & complete video verification", dayOffset: 0 },
              { title: "Submit DSC application to certifying authority", dayOffset: 1 },
              { title: "Issue Digital Signature Certificate", dayOffset: 1 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Mobile & email OTP verification",
            ],
          },
          {
            name: "DSC Class III - Organization",
            slug: "dsc-class-iii-organization",
            basePricePaise: 129900,
            estimatedDays: 1,
            isRecurring: false,
            checklistTemplate: [
              { title: "Collect applicant documents & complete video verification", dayOffset: 0 },
              { title: "Submit DSC application to certifying authority", dayOffset: 1 },
              { title: "Issue Digital Signature Certificate", dayOffset: 1 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Mobile & email OTP verification",
            ],
          },
          {
            name: "DSC Class III - Sign & Encryption",
            slug: "dsc-class-iii-sign-encryption",
            basePricePaise: 249900,
            estimatedDays: 1,
            isRecurring: false,
            checklistTemplate: [
              { title: "Collect applicant documents & complete video verification", dayOffset: 0 },
              { title: "Submit DSC application to certifying authority", dayOffset: 1 },
              { title: "Issue Digital Signature Certificate", dayOffset: 1 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Mobile & email OTP verification",
            ],
          },
          {
            name: "DSC Class III - DGFT",
            slug: "dsc-class-iii-dgft",
            basePricePaise: 299900,
            estimatedDays: 1,
            isRecurring: false,
            checklistTemplate: [
              { title: "Collect applicant documents & complete video verification", dayOffset: 0 },
              { title: "Submit DSC application to certifying authority", dayOffset: 1 },
              { title: "Issue Digital Signature Certificate", dayOffset: 1 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Aadhaar Card",
              "Passport-size photograph",
              "Mobile & email OTP verification",
            ],
          },
        ],
      },
      {
        name: "Licensing Services",
        sort: 3,
        services: [
          {
            name: "FSSAI State License",
            slug: "fssai-state-license",
            basePricePaise: 799900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to licensing authority", dayOffset: 6 },
              { title: "Inspection/verification (if applicable)", dayOffset: 10 },
              { title: "Receive license", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
          {
            name: "FSSAI Central License",
            slug: "fssai-central-license",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to licensing authority", dayOffset: 6 },
              { title: "Inspection/verification (if applicable)", dayOffset: 10 },
              { title: "Receive license", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
          {
            name: "Shops & Establishment License",
            slug: "shops-establishment-license",
            basePricePaise: 299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to licensing authority", dayOffset: 6 },
              { title: "Inspection/verification (if applicable)", dayOffset: 10 },
              { title: "Receive license", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
          {
            name: "Fire License",
            slug: "fire-license",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to licensing authority", dayOffset: 6 },
              { title: "Inspection/verification (if applicable)", dayOffset: 10 },
              { title: "Receive license", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
          {
            name: "Labour License",
            slug: "labour-license",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to licensing authority", dayOffset: 6 },
              { title: "Inspection/verification (if applicable)", dayOffset: 10 },
              { title: "Receive license", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
          {
            name: "Trade License",
            slug: "trade-license",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 3 },
              { title: "Submit application to licensing authority", dayOffset: 6 },
              { title: "Inspection/verification (if applicable)", dayOffset: 10 },
              { title: "Receive license", dayOffset: 15 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
          {
            name: "Drug License",
            slug: "drug-license",
            basePricePaise: 3999900,
            estimatedDays: 25,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare application & documents", dayOffset: 5 },
              { title: "Submit application to licensing authority", dayOffset: 10 },
              { title: "Inspection/verification (if applicable)", dayOffset: 18 },
              { title: "Receive license", dayOffset: 25 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Business address proof",
              "Premises ownership/rental proof",
            ],
          },
        ],
      },
      {
        name: "ISO Certification",
        sort: 4,
        services: [
          {
            name: "ISO 9001:2015 Certification",
            slug: "iso-certification",
            description: "ISO 9001/certification consulting and audit coordination.",
            basePricePaise: 299900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 3 },
              { title: "Documentation & QMS setup", dayOffset: 3 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 14001:2015 Certification",
            slug: "iso-14001-2015-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 45001:2018 Certification",
            slug: "iso-45001-2018-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 27001:2013 Certification",
            slug: "iso-27001-2013-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 20000-1:2018 Certification",
            slug: "iso-20000-1-2018-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO GMP Certification",
            slug: "iso-gmp-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 22000:2018 Certification",
            slug: "iso-22000-2018-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 50001:2018 Certification",
            slug: "iso-50001-2018-certification",
            basePricePaise: 600000,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
          {
            name: "ISO 13485:2016 Certification",
            slug: "iso-13485-2016-certification",
            basePricePaise: 499900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gap assessment", dayOffset: 1 },
              { title: "Documentation & management system setup", dayOffset: 2 },
              { title: "Coordinate certification audit", dayOffset: 3 },
              { title: "Receive ISO certificate", dayOffset: 3 },
            ],
            requiredDocuments: ["Business registration proof", "Process documentation"],
          },
        ],
      },
      {
        name: "IPR Services",
        sort: 5,
        services: [
          {
            name: "Trademark Registration",
            slug: "trademark-registration",
            description: "Trademark search, filing and prosecution.",
            basePricePaise: 699900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Conduct trademark search", dayOffset: 2 },
              { title: "Prepare & file TM-A application", dayOffset: 5 },
              { title: "Receive filing acknowledgement", dayOffset: 5 },
              { title: "Track examination report", dayOffset: 5 },
            ],
            requiredDocuments: [
              "Logo/wordmark",
              "Applicant identity proof",
              "Business proof (if applicable)",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Accounting & Auditing Services",
    sort: 3,
    categories: [
      {
        name: "GST Return Filing",
        sort: 1,
        services: [
          {
            name: "GST Filing",
            slug: "gst-monthly-filing",
            description: "Recurring monthly GSTR-1 and GSTR-3B filing.",
            basePricePaise: 49900,
            estimatedDays: 1,
            isRecurring: true,
            recurrence: "monthly",
            checklistTemplate: [
              { title: "Collect sales/purchase data", dayOffset: 1 },
              { title: "Reconcile ITC", dayOffset: 1 },
              { title: "File GSTR-1", dayOffset: 1 },
              { title: "File GSTR-3B", dayOffset: 1 },
            ],
            requiredDocuments: ["Sales register", "Purchase register", "Bank statement"],
          },
        ],
      },
      {
        name: "Accounting Services",
        sort: 2,
        services: [
          {
            name: "TDS Return Filing",
            slug: "tds-return-filing",
            basePricePaise: 49900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "quarterly",
            checklistTemplate: [
              { title: "Collect financial records", dayOffset: 2 },
              { title: "Prepare & reconcile accounts", dayOffset: 4 },
              { title: "Deliver report/filing", dayOffset: 5 },
            ],
            requiredDocuments: ["Sales register", "Purchase register", "Bank statement"],
          },
          {
            name: "Professional Tax Filing",
            slug: "professional-tax-filing",
            basePricePaise: 99900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "monthly",
            checklistTemplate: [
              { title: "Collect financial records", dayOffset: 2 },
              { title: "Prepare & reconcile accounts", dayOffset: 4 },
              { title: "Deliver report/filing", dayOffset: 5 },
            ],
            requiredDocuments: ["Sales register", "Purchase register", "Bank statement"],
          },
          {
            name: "Maintaining Books of Accounts",
            slug: "maintaining-books-of-accounts",
            basePricePaise: 299900,
            estimatedDays: 30,
            isRecurring: true,
            recurrence: "monthly",
            checklistTemplate: [
              { title: "Collect financial records", dayOffset: 9 },
              { title: "Prepare & reconcile accounts", dayOffset: 21 },
              { title: "Deliver report/filing", dayOffset: 30 },
            ],
            requiredDocuments: ["Sales register", "Purchase register", "Bank statement"],
          },
        ],
      },
      {
        name: "Auditing Services",
        sort: 3,
        services: [
          {
            name: "IT Return - Salaried & Non-salaried",
            slug: "it-return-salaried-non-salaried",
            basePricePaise: 99900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Collect income/financial documents", dayOffset: 2 },
              { title: "Compute liability / prepare report", dayOffset: 3 },
              { title: "File return / submit report", dayOffset: 4 },
              { title: "Share acknowledgement", dayOffset: 5 },
            ],
            requiredDocuments: ["PAN Card", "Bank statement", "Financial statements"],
          },
          {
            name: "IT Return - Firm",
            slug: "it-return-firm",
            basePricePaise: 499900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Collect income/financial documents", dayOffset: 2 },
              { title: "Compute liability / prepare report", dayOffset: 3 },
              { title: "File return / submit report", dayOffset: 4 },
              { title: "Share acknowledgement", dayOffset: 5 },
            ],
            requiredDocuments: ["PAN Card", "Bank statement", "Financial statements"],
          },
          {
            name: "IT Return - Companies",
            slug: "it-return-companies",
            basePricePaise: 999900,
            estimatedDays: 7,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Collect income/financial documents", dayOffset: 2 },
              { title: "Compute liability / prepare report", dayOffset: 4 },
              { title: "File return / submit report", dayOffset: 6 },
              { title: "Share acknowledgement", dayOffset: 7 },
            ],
            requiredDocuments: ["PAN Card", "Bank statement", "Financial statements"],
          },
          {
            name: "Internal Audit",
            slug: "internal-audit",
            basePricePaise: 1999900,
            estimatedDays: 30,
            isRecurring: false,
            checklistTemplate: [
              { title: "Collect income/financial documents", dayOffset: 9 },
              { title: "Compute liability / prepare report", dayOffset: 18 },
              { title: "File return / submit report", dayOffset: 26 },
              { title: "Share acknowledgement", dayOffset: 30 },
            ],
            requiredDocuments: ["PAN Card", "Bank statement", "Financial statements"],
          },
          {
            name: "Provisional Finance",
            slug: "provisional-finance",
            basePricePaise: 499900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Collect income/financial documents", dayOffset: 2 },
              { title: "Compute liability / prepare report", dayOffset: 3 },
              { title: "File return / submit report", dayOffset: 4 },
              { title: "Share acknowledgement", dayOffset: 5 },
            ],
            requiredDocuments: ["PAN Card", "Bank statement", "Financial statements"],
          },
          {
            name: "ITR Filing",
            slug: "itr-filing",
            description: "Recurring annual Income Tax Return filing.",
            basePricePaise: 249900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Collect Form 16 / income details", dayOffset: 1 },
              { title: "Compute tax liability", dayOffset: 3 },
              { title: "File return", dayOffset: 4 },
              { title: "Share acknowledgement (ITR-V)", dayOffset: 5 },
            ],
            requiredDocuments: [
              "PAN Card",
              "Form 16 / income proof",
              "Bank statement",
              "Investment proofs",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Secretarial Compliances Services",
    sort: 4,
    categories: [
      {
        name: "Secretarial Compliances",
        sort: 1,
        services: [
          {
            name: "Change of Capital",
            slug: "change-of-capital",
            basePricePaise: 299900,
            estimatedDays: 2,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 1 },
              { title: "File form with ROC", dayOffset: 1 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 2 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Change of Name",
            slug: "change-of-name",
            basePricePaise: 299900,
            estimatedDays: 2,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 1 },
              { title: "File form with ROC", dayOffset: 1 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 2 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Change of Address",
            slug: "change-of-address",
            basePricePaise: 299900,
            estimatedDays: 2,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 1 },
              { title: "File form with ROC", dayOffset: 1 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 2 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Change of Objective",
            slug: "change-of-objective",
            basePricePaise: 299900,
            estimatedDays: 2,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 1 },
              { title: "File form with ROC", dayOffset: 1 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 2 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "DIN KYC",
            slug: "dir-3-kyc",
            description: "Recurring yearly KYC filing for directors.",
            basePricePaise: 99900,
            estimatedDays: 2,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Collect director KYC documents", dayOffset: 1 },
              { title: "File DIR-3 KYC", dayOffset: 2 },
            ],
            requiredDocuments: ["PAN Card", "Aadhaar Card", "Mobile & email OTP verification"],
          },
          {
            name: "Addition of Director",
            slug: "addition-of-director",
            basePricePaise: 299900,
            estimatedDays: 2,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 1 },
              { title: "File form with ROC", dayOffset: 1 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 2 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Removal of Director",
            slug: "removal-of-director",
            basePricePaise: 299900,
            estimatedDays: 2,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 1 },
              { title: "File form with ROC", dayOffset: 1 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 2 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Annual Compliances for Company",
            slug: "annual-compliance-pvt-ltd",
            description: "Recurring yearly ROC annual filing for Private Limited companies.",
            basePricePaise: 499900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Prepare financial statements", dayOffset: 5 },
              { title: "Conduct board meeting & AGM", dayOffset: 5 },
              { title: "File AOC-4", dayOffset: 5 },
              { title: "File MGT-7", dayOffset: 5 },
            ],
            requiredDocuments: ["Financial statements", "Board resolutions", "Audit report"],
          },
          {
            name: "Annual Compliances for LLP",
            slug: "annual-compliance-llp",
            description: "Recurring yearly ROC annual filing for LLPs.",
            basePricePaise: 499900,
            estimatedDays: 5,
            isRecurring: true,
            recurrence: "yearly",
            checklistTemplate: [
              { title: "Prepare statement of accounts", dayOffset: 5 },
              { title: "File Form 8", dayOffset: 5 },
              { title: "File Form 11", dayOffset: 5 },
            ],
            requiredDocuments: ["Statement of accounts & solvency", "Partner KYC"],
          },
          {
            name: "Increased Authorized Capital",
            slug: "increased-authorized-capital",
            basePricePaise: 299900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 2 },
              { title: "File form with ROC", dayOffset: 4 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 5 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Closure of Company",
            slug: "closure-of-company",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 4 },
              { title: "File form with ROC", dayOffset: 10 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 15 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Change of LLP Agreement",
            slug: "change-of-llp-agreement",
            basePricePaise: 299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 4 },
              { title: "File form with ROC", dayOffset: 10 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 15 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Closure of LLP",
            slug: "closure-of-llp",
            basePricePaise: 1299900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 4 },
              { title: "File form with ROC", dayOffset: 10 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 15 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Commencement of Business",
            slug: "commencement-of-business",
            basePricePaise: 299900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 2 },
              { title: "File form with ROC", dayOffset: 4 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 5 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Appointment of Auditor(ADT-1)",
            slug: "appointment-of-auditor-adt-1",
            basePricePaise: 299900,
            estimatedDays: 5,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 2 },
              { title: "File form with ROC", dayOffset: 4 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 5 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
          {
            name: "Aadhar PAN Link",
            slug: "aadhar-pan-link",
            basePricePaise: 39900,
            estimatedDays: 15,
            isRecurring: false,
            checklistTemplate: [
              { title: "Prepare board/partner resolution", dayOffset: 4 },
              { title: "File form with ROC", dayOffset: 10 },
              { title: "Receive ROC approval/acknowledgement", dayOffset: 15 },
            ],
            requiredDocuments: [
              "Board/partner resolution",
              "Company/LLP incorporation documents",
              "Digital Signature Certificate",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "IT Services",
    sort: 5,
    categories: [
      {
        name: "Information Technology",
        sort: 1,
        services: [
          {
            name: "Domain Registration",
            slug: "domain-registration",
            basePricePaise: 89900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gather requirements & credentials", dayOffset: 1 },
              { title: "Provision/set up service", dayOffset: 2 },
              { title: "Handover access & confirmation", dayOffset: 3 },
            ],
            requiredDocuments: [
              "Business registration/ID proof",
              "Domain/hosting preference details",
            ],
          },
          {
            name: "Hosting Services",
            slug: "hosting-services",
            basePricePaise: 99900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gather requirements & credentials", dayOffset: 1 },
              { title: "Provision/set up service", dayOffset: 2 },
              { title: "Handover access & confirmation", dayOffset: 3 },
            ],
            requiredDocuments: [
              "Business registration/ID proof",
              "Domain/hosting preference details",
            ],
          },
          {
            name: "Web Designing",
            slug: "web-designing",
            basePricePaise: 299900,
            estimatedDays: 7,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gather requirements & credentials", dayOffset: 2 },
              { title: "Provision/set up service", dayOffset: 5 },
              { title: "Handover access & confirmation", dayOffset: 7 },
            ],
            requiredDocuments: [
              "Business registration/ID proof",
              "Domain/hosting preference details",
            ],
          },
          {
            name: "Business Email",
            slug: "business-email",
            basePricePaise: 89900,
            estimatedDays: 3,
            isRecurring: false,
            checklistTemplate: [
              { title: "Gather requirements & credentials", dayOffset: 1 },
              { title: "Provision/set up service", dayOffset: 2 },
              { title: "Handover access & confirmation", dayOffset: 3 },
            ],
            requiredDocuments: [
              "Business registration/ID proof",
              "Domain/hosting preference details",
            ],
          },
        ],
      },
    ],
  },
];
