export type ClientSeed = {
  type: "individual" | "business";
  name: string;
  businessName?: string;
  phone: string;
  email?: string;
  gstin?: string;
  pan?: string;
  address?: string;
  city: string;
  state: string;
  pincode: string;
  referralSource?: string;
};

export const CLIENT_SEED: ClientSeed[] = [
  {
    type: "business",
    name: "Rajesh Kumar",
    businessName: "Kumar Textiles Pvt Ltd",
    phone: "+919810011122",
    email: "rajesh@kumartextiles.in",
    pan: "AAACK1234L",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    referralSource: "referral",
  },
  {
    type: "individual",
    name: "Priya Sharma",
    phone: "+919820033344",
    email: "priya.sharma@gmail.com",
    pan: "BXNPS4567Q",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400001",
    referralSource: "google",
  },
  {
    type: "business",
    name: "Anil Mehta",
    businessName: "Mehta Exports LLP",
    phone: "+919830055566",
    email: "anil@mehtaexports.com",
    gstin: "27AACFM1234A1Z5",
    pan: "AACFM1234A",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411001",
    referralSource: "website",
  },
  {
    type: "individual",
    name: "Sneha Reddy",
    phone: "+919840077788",
    email: "sneha.reddy@yahoo.com",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500001",
    referralSource: "whatsapp",
  },
  {
    type: "business",
    name: "Vikram Singh",
    businessName: "Singh Traders",
    phone: "+919850099911",
    email: "vikram@singhtraders.in",
    gstin: "08AABFS5678B1Z2",
    pan: "AABFS5678B",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    referralSource: "meta_ads",
  },
  {
    type: "individual",
    name: "Kavita Nair",
    phone: "+919860011223",
    email: "kavita.nair@gmail.com",
    city: "Kochi",
    state: "Kerala",
    pincode: "682001",
    referralSource: "referral",
  },
  {
    type: "business",
    name: "Arjun Gupta",
    businessName: "Gupta Consultants OPC",
    phone: "+919870033445",
    email: "arjun@guptaconsult.in",
    pan: "AAECG4321C",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560001",
    referralSource: "google",
  },
  {
    type: "individual",
    name: "Meera Iyer",
    phone: "+919880055667",
    email: "meera.iyer@outlook.com",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600001",
    referralSource: "walk_in",
  },
  {
    type: "business",
    name: "Suresh Patel",
    businessName: "Patel Agro Foods",
    phone: "+919890077889",
    email: "suresh@patelagro.in",
    gstin: "24AAACP9876D1Z8",
    pan: "AAACP9876D",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380001",
    referralSource: "referral",
  },
  {
    type: "individual",
    name: "Divya Rao",
    phone: "+919900099001",
    email: "divya.rao@gmail.com",
    city: "Nagpur",
    state: "Maharashtra",
    pincode: "440001",
    referralSource: "website",
  },
  {
    type: "business",
    name: "Ramesh Chandra",
    businessName: "Chandra Logistics Pvt Ltd",
    phone: "+919910011234",
    email: "ramesh@chandralogistics.in",
    gstin: "09AABFC6543E1Z1",
    pan: "AABFC6543E",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
    referralSource: "meta_ads",
  },
  {
    type: "individual",
    name: "Anjali Desai",
    phone: "+919920022345",
    email: "anjali.desai@gmail.com",
    city: "Surat",
    state: "Gujarat",
    pincode: "395001",
    referralSource: "whatsapp",
  },
  {
    type: "business",
    name: "Manoj Verma",
    businessName: "Verma Electricals",
    phone: "+919930033456",
    email: "manoj@vermaelectricals.in",
    pan: "AAJPV2345F",
    city: "Kanpur",
    state: "Uttar Pradesh",
    pincode: "208001",
    referralSource: "referral",
  },
  {
    type: "individual",
    name: "Pooja Joshi",
    phone: "+919940044567",
    email: "pooja.joshi@gmail.com",
    city: "Indore",
    state: "Madhya Pradesh",
    pincode: "452001",
    referralSource: "google",
  },
  {
    type: "business",
    name: "Karan Malhotra",
    businessName: "Malhotra Interiors LLP",
    phone: "+919950055678",
    email: "karan@malhotrainteriors.in",
    gstin: "07AAAFM3456G1Z6",
    pan: "AAAFM3456G",
    city: "Delhi",
    state: "Delhi",
    pincode: "110019",
    referralSource: "website",
  },
  {
    type: "individual",
    name: "Neha Kapoor",
    phone: "+919960066789",
    email: "neha.kapoor@gmail.com",
    city: "Chandigarh",
    state: "Punjab",
    pincode: "160001",
    referralSource: "walk_in",
  },
  {
    type: "business",
    name: "Deepak Bansal",
    businessName: "Bansal Pharma Distributors",
    phone: "+919970077890",
    email: "deepak@bansalpharma.in",
    gstin: "06AABFB7890H1Z4",
    pan: "AABFB7890H",
    city: "Ludhiana",
    state: "Punjab",
    pincode: "141001",
    referralSource: "referral",
  },
  {
    type: "individual",
    name: "Ritu Agarwal",
    phone: "+919980088901",
    email: "ritu.agarwal@gmail.com",
    city: "Patna",
    state: "Bihar",
    pincode: "800001",
    referralSource: "meta_ads",
  },
  {
    type: "business",
    name: "Sanjay Bhatt",
    businessName: "Bhatt Enterprises",
    phone: "+919990099012",
    email: "sanjay@bhattenterprises.in",
    pan: "AAJPB6789K",
    city: "Bhopal",
    state: "Madhya Pradesh",
    pincode: "462001",
    referralSource: "google",
  },
  {
    type: "individual",
    name: "Isha Chatterjee",
    phone: "+919000011123",
    email: "isha.chatterjee@gmail.com",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700001",
    referralSource: "whatsapp",
  },
];
